import { useEffect, useState, useRef } from 'react';
import { Copy, Download, RefreshCw, ExternalLink, Plus, ChevronUp, ChevronDown, X, Info } from 'lucide-react';
import { api, Modal, Field, Status, dateText } from './ui';
import { errorText, ApiError } from './api';
import './metadata.css';

type Author={name:string;kind?:string;given?:string;family?:string;affiliations?:string[]};
type Link={kind:string;url:string;label?:string;source?:string};
type Fields=Record<string,any> & {author_list:Author[];links:Link[]};
type Metadata={revision:number;fields:Fields;provenance:Record<string,any>;candidates:any[];task:any;indexPending:boolean;originalTitle:string};
const labels:Record<string,string>={title:'标题',authors:'作者原文',affiliation:'作者机构',year:'显示年份',journal:'会议／期刊',abstract:'作者摘要',doi:'DOI',arxiv_id:'arXiv ID',arxiv_version:'arXiv 版本',source_url:'来源链接',homepage:'项目主页',github:'代码仓库',venue_type:'文献类型',volume:'卷',issue:'期',pages:'页码',published_date:'正式发表日期',preprint_date:'预印本首次提交',version_date:'版本更新时间',author_list:'有序作者',links:'项目与数据链接'};
const sources:Record<string,string>={manual:'人工编辑',legacy:'历史记录，来源未核实',legacy_edit:'旧版本中的人工修改',import:'导入记录',filename:'导入文件名',pdf_embedded:'PDF 内嵌信息',arxiv:'arXiv',crossref:'Crossref',dblp:'DBLP',openreview:'OpenReview'};
export const metadataStatus:Record<string,string>={queued:'等待补全',waiting:'等待来源服务',running:'正在补全',completed:'已补全',unchanged:'现有信息已保留',needs_review:'有候选信息待核对',not_found:'未找到可核实的书目',failed:'补全失败，可重试',cancelled:'已取消',stale:'信息已修改，请重新补全',deleted:'论文已移除'};
export const metadataErrors:Record<string,string>={invalid_metadata_date:'日期格式应为 YYYY、YYYY-MM 或有效的 YYYY-MM-DD',invalid_metadata_url:'请输入完整的 HTTP 或 HTTPS 链接',invalid_doi:'DOI 格式不正确，请核对标识符',invalid_arxiv_id:'arXiv ID 或版本格式不正确',invalid_authors:'请填写作者姓名，并核对作者列表',invalid_project_links:'请填写有效的项目链接',invalid_metadata_field:'字段内容不符合要求，请核对长度和格式',metadata_nothing_to_retry:'没有需要重试的失败项',metadata_candidate_not_found:'候选已更新，请重新载入来源',metadata_redirect_blocked:'来源返回了未允许的跳转',metadata_provider_unavailable:'书目来源暂时不可用',metadata_rate_limited:'书目来源限流，将按等待时间继续',metadata_timeout:'书目来源响应超时',metadata_network_failed:'书目来源暂时无法连接',metadata_access_denied:'书目来源拒绝访问',metadata_outbound_blocked:'书目来源连接未通过出站校验',metadata_request_budget:'已达到本篇请求上限，可手动重试',metadata_revision_conflict:'信息已在其他操作中更新。草稿已保留，请重新载入后核对。',metadata_storage_failed:'信息未能保存，请重试',metadata_processing_failed:'补全未完成，请在任务中心重试',metadata_source_changed:'原文件版本已变化，请重新核对',metadata_invalid_response:'书目来源返回的内容无法识别',metadata_document_unavailable:'无法读取本地文档信息'};
function message(e:unknown){return e instanceof ApiError && metadataErrors[e.code] ? metadataErrors[e.code] : errorText(e);}
function useMetadata(id:string, refresh=0, poll=true){const [data,setData]=useState<Metadata|null>(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;
  async function load(){try{const r=await api(`/api/paper/${encodeURIComponent(id)}/metadata`,'GET',undefined,controller.signal);if(alive){setData(r);setError('');if(poll&&(r.indexPending||(r.task&&['queued','waiting','running'].includes(r.task.status))))timer=setTimeout(load,3000);}}catch(e){if(alive&&!controller.signal.aborted)setError(message(e));}}
  setData(null);void load();return()=>{alive=false;controller.abort();clearTimeout(timer)};
 },[id,refresh,poll]);return {data,error,setData,setError};}

export function MetadataDetails({id,onChanged,onSelect}:{id:string;onChanged:()=>void;onSelect:(id:string)=>void}){
 const [refresh,setRefresh]=useState(0);const {data,error,setData,setError}=useMetadata(id,refresh);const current=useRef(id);current.current=id;const done=useRef('');const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[sourcesOpen,setSourcesOpen]=useState(false),[duplicates,setDuplicates]=useState<any[]>([]);
 useEffect(()=>{let alive=true;api(`/api/paper/${id}/duplicates`).then(x=>{if(alive)setDuplicates(x.items)}).catch(()=>{});return()=>{alive=false}},[id,data?.revision]);
 useEffect(()=>{const token=data?.task?.id+':'+data?.task?.status+':'+data?.indexPending;if(data?.task&&!['queued','waiting','running'].includes(data.task.status)&&done.current!==token){done.current=token;onChanged()}},[data?.task?.id,data?.task?.status,data?.indexPending]);
 useEffect(()=>{setNotice('');setBusy(false);setSourcesOpen(false);setDuplicates([])},[id]);
 async function complete(){const paperId=id;setBusy(true);setError('');try{await api('/api/metadata/jobs','POST',{paperIds:[id],force:!!data?.task&&!['queued','waiting','running'].includes(data.task.status)});if(current.current===paperId){setNotice('补全已加入任务中心，当前论文仍可正常阅读。');setRefresh(v=>v+1)}}catch(e){if(current.current===paperId)setError(message(e))}finally{if(current.current===paperId)setBusy(false)}}
 async function copy(){try{const r=await api(`/api/paper/${id}/bibtex`);await navigator.clipboard.writeText(r.bibtex);setNotice('BibTeX 已复制，内容对应当前书目信息。')}catch(e){setError(message(e))}}
 if(!data)return <section className="detail-section"><Status loading={!error} error={error}/></section>;
 const f=data.fields;
 return <section className="detail-section metadata-details">
  <div className="metadata-heading"><span className="section-label">文献信息</span><button className="text-button" onClick={()=>setSourcesOpen(!sourcesOpen)} aria-expanded={sourcesOpen}><Info size={14}/>来源</button></div>
  <div className="metadata-status" role="status">{data.task?metadataStatus[data.task.status]:'信息可后台补全'}{data.indexPending&&<small>搜索索引同步中</small>}</div>
  {f.authors&&<details className="metadata-full-authors"><summary>完整作者{f.author_list.length?`（${f.author_list.length} 位）`:""}</summary><p>{f.author_list.length?f.author_list.map(a=>a.name).join("; "):f.authors}</p></details>}
  <dl>{['year','journal','doi','arxiv_id','arxiv_version','published_date','preprint_date','version_date'].map(key=>f[key]?<div key={key}><dt>{labels[key]}</dt><dd>{key.endsWith('date')?dateText(f[key]):f[key]}</dd></div>:null)}</dl>
  {f.affiliation&&<p className="metadata-affiliation">机构：{f.affiliation}</p>}
  <div className="metadata-actions"><button disabled={busy||['queued','waiting','running'].includes(data.task?.status)} onClick={()=>void complete()}><RefreshCw size={14}/>{busy?'补全进行中':'补全信息'}</button><button onClick={()=>void copy()}><Copy size={14}/>复制引用</button><a className="button" href={`/api/paper/${id}/bibtex?download=1`}><Download size={14}/>BibTeX</a></div>
  {(['homepage','github','source_url'] as const).map(key=>f[key]&&/^https?:\/\//.test(f[key])?<a className="text-button" key={key} href={f[key]} rel="noreferrer noopener" target="_blank">{labels[key]}<ExternalLink size={13}/></a>:null)}
  {f.links?.filter((l:Link)=>/^https?:\/\//.test(l.url)).map((l:Link,i:number)=><a className="text-button" key={i} href={l.url} rel="noreferrer noopener" target="_blank">{l.label||({project:'项目主页',code:'代码',data:'数据',source:'来源'} as any)[l.kind]}<ExternalLink size={13}/></a>)}
  {notice&&<p className="metadata-hint" role="status">{notice}</p>}<Status error={error||metadataErrors[data.task?.error]||''}/>
  {!!duplicates.length&&<div className="metadata-duplicates"><strong>可能已在文献库中</strong>{duplicates.map(d=><div key={d.paperId}><small>{({same_file:'文件内容相同',same_paper:'相同论文标识',related_version:'同篇的相关版本',possible_duplicate:'标题和作者相近'} as any)[d.kind]}</small><button className="text-button" onClick={()=>onSelect(d.paperId)}>{d.title}</button><button className="text-button" onClick={async()=>{try{await api(`/api/paper/${id}/duplicates/dismiss`,'POST',{paperId:d.paperId,signature:d.signature});setDuplicates(duplicates.filter(x=>x.paperId!==d.paperId))}catch(e){setError(message(e))}}}>忽略提示</button></div>)}<small>不会自动合并或删除文件。</small></div>}
  {sourcesOpen&&<MetadataSources id={id} data={data} onSaved={r=>{setData(r);onChanged()}}/>}
 </section>
}
function MetadataSources({id,data,onSaved}:{id:string;data:Metadata;onSaved:(d:Metadata)=>void}){
 const [error,setError]=useState(''),[selected,setSelected]=useState<Record<string,string[]>>({});
 return <div className="metadata-sources"><h3>当前字段来源</h3><dl>{Object.entries(data.provenance).map(([k,p])=><div key={k}><dt>{labels[k]||k}</dt><dd>{sources[p.source]||p.source}{p.manual?' · 已保护':''}{p.url&&/^https?:\/\//.test(p.url)&&<a href={p.url} target="_blank" rel="noreferrer noopener">核对来源</a>}</dd></div>)}</dl>
 {!!data.candidates.length&&<h3>可核对的书目信息</h3>}{data.candidates.map(c=><details key={c.id}><summary>{sources[c.provider]||c.provider} · {c.fields.title||'书目记录'}</summary>{c.relations?.onlineVersion&&<p>线上最新版本 v{c.relations.onlineVersion}；尚未确认与当前文件相同，文件版本保持不变。</p>}<p>逐项核对后采用；不会替换论文文件。</p>{Object.entries(c.fields).filter(([k,v])=>v&&JSON.stringify(v)!==JSON.stringify(data.fields[k])&&k!=='authors').map(([k,v])=><label className="metadata-candidate" key={k}><input type="checkbox" checked={(selected[c.id]||[]).includes(k)} onChange={e=>setSelected({...selected,[c.id]:e.target.checked?[...(selected[c.id]||[]),k]:(selected[c.id]||[]).filter(x=>x!==k)})}/><span><strong>{labels[k]}</strong><span>{k==='author_list'?(v as Author[]).map(a=>a.name).join('; '):k==='links'?(v as Link[]).map(l=>l.url).join('\n'):String(v)}</span></span></label>)}<button disabled={!selected[c.id]?.length} onClick={async()=>{try{onSaved(await api(`/api/paper/${id}/metadata/adopt`,'POST',{candidateId:c.id,revision:data.revision,fields:selected[c.id]}));setSelected({})}catch(e){setError(message(e))}}}>采用选中信息</button></details>)}<Status error={error}/>
 </div>
}

export function MetadataEditor({id,onClose,onSaved}:{id:string;onClose:()=>void;onSaved:()=>void}){
 const {data,error,setError,setData}=useMetadata(id,0,false);const [draft,setDraft]=useState<Fields|null>(null),[busy,setBusy]=useState(false);const touched=useRef(new Set<string>());
 useEffect(()=>{if(data&&!draft)setDraft(structuredClone(data.fields))},[data,draft]);
 const change=(k:string,v:any)=>{touched.current.add(k);setDraft(draft?{...draft,[k]:v}:draft)};
 async function save(e:React.FormEvent){e.preventDefault();if(!draft||!data)return;setBusy(true);setError('');try{const fields=Object.fromEntries(Object.entries(draft).filter(([k,v])=>touched.current.has(k)||JSON.stringify(v)!==JSON.stringify(data.fields[k])));await api(`/api/paper/${id}/metadata`,'PATCH',{revision:data.revision,fields});onSaved();onClose()}catch(e){setError(message(e))}finally{setBusy(false)}}
 return <Modal title="编辑论文信息" onClose={onClose} wide><form className="metadata-editor" onSubmit={save}><p className="metadata-hint">修改和主动清空的字段会受到保护。保存仅更新书目，不改变文件或触发联网请求。</p><Status loading={!draft&&!error} error={error}/>
 {draft&&<><Field label="标题"><textarea rows={2} value={draft.title} onChange={e=>change('title',e.target.value)}/></Field>
 <fieldset><legend>完整作者 · 保留顺序</legend>{!draft.author_list.length&&draft.authors&&<Field label="历史作者原文（尚未拆分）"><textarea value={draft.authors} onChange={e=>change('authors',e.target.value)}/></Field>}
 {draft.author_list.map((a,i)=><div className="metadata-author" key={i}><input aria-label={`第 ${i+1} 位作者`} value={a.name} onChange={e=>change('author_list',draft.author_list.map((x,j)=>j===i?{...x,name:e.target.value,given:'',family:''}:x))}/><select aria-label={`第 ${i+1} 位作者类型`} value={a.kind||'person'} onChange={e=>change('author_list',draft.author_list.map((x,j)=>j===i?{...x,kind:e.target.value}:x))}><option value="person">个人</option><option value="organization">团体</option></select>{[-1,1].map(dir=><button type="button" key={dir} aria-label={dir===-1?'作者上移':'作者下移'} disabled={i+dir<0||i+dir>=draft.author_list.length} onClick={()=>{const next=[...draft.author_list];[next[i],next[i+dir]]=[next[i+dir],next[i]];change('author_list',next)}}>{dir===-1?<ChevronUp size={14}/>:<ChevronDown size={14}/>}</button>)}<button type="button" aria-label="移除作者" onClick={()=>change('author_list',draft.author_list.filter((_,j)=>j!==i))}><X size={14}/></button></div>)}
 <button type="button" className="text-button" onClick={()=>change('author_list',[...draft.author_list,{name:'',kind:'person'}])}><Plus size={14}/>添加作者</button></fieldset>
 <div className="metadata-form-grid">{['affiliation','year','journal','venue_type','doi','arxiv_id','arxiv_version','published_date','preprint_date','version_date','volume','issue','pages','source_url','homepage','github'].map(k=><Field key={k} label={labels[k]}>{k==='venue_type'?<select value={draft[k]} onChange={e=>change(k,e.target.value)}>{[['','未确认'],['journal','期刊论文'],['conference','会议论文'],['preprint','预印本'],['submission','投稿'],['other','其他']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input value={draft[k]} onChange={e=>change(k,e.target.value)} placeholder={k.endsWith('date')?'YYYY-MM-DD':''}/>}</Field>)}</div>
 <Field label="作者摘要"><textarea rows={8} value={draft.abstract} onChange={e=>change('abstract',e.target.value)}/></Field>
 <fieldset><legend>项目与数据链接</legend>{draft.links.map((l,i)=><div className="metadata-link-edit" key={i}><select aria-label="链接类型" value={l.kind} onChange={e=>change('links',draft.links.map((x,j)=>j===i?{...x,kind:e.target.value}:x))}>{[['project','项目'],['code','代码'],['data','数据'],['source','来源']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select><input aria-label="链接地址" value={l.url} onChange={e=>change('links',draft.links.map((x,j)=>j===i?{...x,url:e.target.value}:x))}/><button type="button" aria-label="移除链接" onClick={()=>change('links',draft.links.filter((_,j)=>j!==i))}><X size={14}/></button></div>)}<button type="button" className="text-button" onClick={()=>change('links',[...draft.links,{kind:'project',url:'',source:'人工提供'}])}><Plus size={14}/>添加链接</button></fieldset>
 </>}
 <footer><button type="button" onClick={onClose}>取消</button>{error&&<button type="button" onClick={async()=>{try{setData(await api(`/api/paper/${id}/metadata`));setDraft(null);touched.current.clear();setError('')}catch(e){setError(message(e))}}}>重新载入信息</button>}<button className="primary" disabled={busy||!draft}>{busy?'保存中':'保存'}</button></footer></form></Modal>
}

export function MetadataBatchDialog({selection,onClose,onCreated}:{selection:Record<string,unknown>;onClose:()=>void;onCreated:()=>void}){
 const [preview,setPreview]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;api('/api/metadata/preview','POST',selection).then(r=>{if(alive)setPreview(r)}).catch(e=>{if(alive)setError(message(e))});return()=>{alive=false}},[selection]);
 return <Modal title="批量补全论文信息" onClose={onClose}><Status loading={!preview&&!error} error={error}/>{preview&&<><p>将补全 <strong>{preview.count}</strong> 篇已入库论文的信息，覆盖所选范围的全部页面。</p><p>保留人工修改、主动清空和已有可靠信息。任务可取消、重试，重启后继续；论文文件保持原位。</p><p className="metadata-hint">仅查询公开书目；最多 {preview.maximumBibliographicRequests} 次书目请求。不会调用模型、MinerU 或 OCR。</p></>}<footer><button onClick={onClose}>取消</button><button className="primary" disabled={busy||!preview?.count} onClick={async()=>{setBusy(true);try{await api('/api/metadata/jobs','POST',{paperIds:preview.paperIds,force:true});onCreated()}catch(e){setError(message(e))}finally{setBusy(false)}}}>开始补全</button></footer></Modal>
}

export function MetadataTask({id}:{id:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[offset,setOffset]=useState(0);
 async function refresh(){try{setData(await api(`/api/metadata/jobs/${id}?after=${offset}`))}catch(e){setError(message(e))}}
 useEffect(()=>{let alive=true;const load=async()=>{try{const r=await api(`/api/metadata/jobs/${id}?after=${offset}`);if(alive)setData(r)}catch(e){if(alive)setError(message(e))}};void load();const timer=setInterval(load,3000);return()=>{alive=false;clearInterval(timer)}},[id,offset]);
 return <div className="metadata-task"><Status error={error} loading={!data&&!error}/>{data&&<><h3>论文信息补全 · {data.completed} / {data.total}</h3><div className="metadata-actions"><button disabled={data.status!=='running'} onClick={async()=>{try{await api(`/api/metadata/jobs/${id}/cancel`,'POST',{});void refresh()}catch(e){setError(message(e))}}}>取消未完成项</button><button disabled={data.status==='running'} onClick={async()=>{try{await api(`/api/metadata/jobs/${id}/retry`,'POST',{});setError('重试已创建，可在任务列表查看。')}catch(e){setError(message(e))}}}>重试失败项</button></div>{data.items.map((item:any)=><div className="metadata-task-item" key={item.id}><a href={`/?paper=${item.paper_id}`}>查看论文</a><span>{metadataStatus[item.status]}</span>{item.error&&<small>{metadataErrors[item.error]||'任务未完成'}</small>}</div>)}<div className="metadata-actions"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>上一页</button><button disabled={data.next===null} onClick={()=>setOffset(data.next)}>下一页</button></div><details><summary>任务日志</summary>{data.events.map((e:any)=><p key={e.sequence}>{dateText(e.created_at)} · {metadataStatus[e.kind]||({fields_saved:'字段已保存'} as any)[e.kind]||'状态更新'}</p>)}</details></>}</div>
}
